name = "Portfolio Hugo Theme"
license = "MIT"
licenselink = "https://github.com/sizeofvoid/hugo-opp-theme/blob/master/LICENSE.md"
description = "Portfolio theme for Hugo"
homepage = "https://github.com/sizeofvoid/hugo-opp-theme"
tags = ["lodi", "responsive", "hero", "personal", "portfolio" ]
features = ["homepage", "process"]
min_version = "0.0"

[author]
  name = "Rafael Sadowski"
  homepage = "https://github.com/sizeofvoid/"

# If porting an existing theme
[original]
  name = "Xavi Ablaza"
  homepage = "https://github.com/xaviablaza"
  #author = "Alexis Collado"
  #name = "Portfolio"
  #homepage = "http://www.alexiscollado.com"
